include:
  - project: sysadmin/ci-utilities
    file:
      # Re-enable when ported to QtWebEngine
      #- /gitlab-templates/linux.yml
      - /gitlab-templates/xml-lint.yml

# This should go again, if we got rid of QtWebkit
build_fedora:
  stage: build
  image: fedora:42
  tags:
    - Linux
  before_script:
    - dnf upgrade -y
    - dnf install -y kf5-sonnet-devel mimetic-devel ninja qgpgme-qt5-devel qt5-linguist qt5-qtsvg-devel qt5-qtwebkit-devel qtkeychain-qt5-devel ragel
  script:
    - mkdir -p build && cd build
    # Avoid the akonadi addressbook plugin to not make things bigger for now
    - cmake -GNinja -DWITH_AKONADIADDRESSBOOK_PLUGIN=FALSE -DWITH_QTKEYCHAIN_PLUGIN=TRUE -DWITH_RAGEL=TRUE -DWITH_SONNET_PLUGIN=TRUE ..
    - ninja
    # Can't load the xcb platform plugin in the container, guess it would need
    # a xserver, so just use the vnc one.
    - export QT_QPA_PLATFORM=vnc:port=0
    - ctest -V
