# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'pim/akonadi-contacts' : '@same'

Options:
  cmake-options: '-DWITH_WEBKIT=FALSE'
  # TODO force-inject-asan can go once
  # tests/Cryptography/keygen.sh is
  # removed and CMakeLists.txt includes
  # ECMEnableSanitizers or KDECompilerSettings
  force-inject-asan: True
